package com.springboot.demo.util.base.entitypo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;


/**
 * 系统菜单按钮权限表
 **/
@Entity
public class SysAction extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ACTION.ID
     *
     * @mbggenerated Mon Mar 06 14:07:05 CST 2017
     */
    @Id
    @Column(nullable = false, length = 24)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ACTION.MODULE_ID
     *
     * @mbggenerated Mon Mar 06 14:07:05 CST 2017
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ACTION.ACTION_CODE
     *
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    private String actionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ACTION.ACTION_NAME
     *
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    private String actionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ACTION.ENABLE_STATE
     *
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    private String enableState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ACTION.ORDER_ID
     *
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    private BigDecimal orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ACTION.ID
     *
     * @return the value of SYS_ACTION.ID
     * @mbggenerated Mon Mar 06 14:07:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ACTION.ID
     *
     * @param id the value for SYS_ACTION.ID
     * @mbggenerated Mon Mar 06 14:07:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ACTION.MODULE_ID
     *
     * @return the value of SYS_ACTION.MODULE_ID
     * @mbggenerated Mon Mar 06 14:07:05 CST 2017
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ACTION.MODULE_ID
     *
     * @param moduleId the value for SYS_ACTION.MODULE_ID
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ACTION.ACTION_CODE
     *
     * @return the value of SYS_ACTION.ACTION_CODE
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ACTION.ACTION_CODE
     *
     * @param actionCode the value for SYS_ACTION.ACTION_CODE
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public void setActionCode(String actionCode) {
        this.actionCode = actionCode == null ? null : actionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ACTION.ACTION_NAME
     *
     * @return the value of SYS_ACTION.ACTION_NAME
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ACTION.ACTION_NAME
     *
     * @param actionName the value for SYS_ACTION.ACTION_NAME
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ACTION.ENABLE_STATE
     *
     * @return the value of SYS_ACTION.ENABLE_STATE
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public String getEnableState() {
        return enableState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ACTION.ENABLE_STATE
     *
     * @param enableState the value for SYS_ACTION.ENABLE_STATE
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public void setEnableState(String enableState) {
        this.enableState = enableState == null ? null : enableState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ACTION.ORDER_ID
     *
     * @return the value of SYS_ACTION.ORDER_ID
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public BigDecimal getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ACTION.ORDER_ID
     *
     * @param orderId the value for SYS_ACTION.ORDER_ID
     * @mbggenerated Mon Mar 06 14:07:06 CST 2017
     */
    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }
}