package com.springboot.demo.util.base.entitypo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;

/**
 * 菜单表
 **/
@Entity
public class SysModule extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.ID
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    @Id
    @Column(nullable = false, length = 24)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.PARENT_ID
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.MODULE_NAME
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.MODULE_CODE
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.MODULE_RESOURCE
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private String moduleResource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.BY_BU
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private BigDecimal byBu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.STATE
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private BigDecimal state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.MODULE_ORDER
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private BigDecimal moduleOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.REMARK
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.NEEDSELECTPROJECT
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private BigDecimal needselectproject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.MODULE_NAME_EN
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private String moduleNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.ISCTRL
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private Short isctrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.HOME_MODULE_ID
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private BigDecimal homeModuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MODULE.SYSTEM_ID
     *
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    private BigDecimal systemId;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.MODULE_NAME
     *
     * @return the value of SYS_MODULE.MODULE_NAME
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.MODULE_NAME
     *
     * @param moduleName the value for SYS_MODULE.MODULE_NAME
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.MODULE_CODE
     *
     * @return the value of SYS_MODULE.MODULE_CODE
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.MODULE_CODE
     *
     * @param moduleCode the value for SYS_MODULE.MODULE_CODE
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode == null ? null : moduleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.MODULE_RESOURCE
     *
     * @return the value of SYS_MODULE.MODULE_RESOURCE
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public String getModuleResource() {
        return moduleResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.MODULE_RESOURCE
     *
     * @param moduleResource the value for SYS_MODULE.MODULE_RESOURCE
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setModuleResource(String moduleResource) {
        this.moduleResource = moduleResource == null ? null : moduleResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.BY_BU
     *
     * @return the value of SYS_MODULE.BY_BU
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public BigDecimal getByBu() {
        return byBu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.BY_BU
     *
     * @param byBu the value for SYS_MODULE.BY_BU
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setByBu(BigDecimal byBu) {
        this.byBu = byBu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.STATE
     *
     * @return the value of SYS_MODULE.STATE
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.STATE
     *
     * @param state the value for SYS_MODULE.STATE
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.MODULE_ORDER
     *
     * @return the value of SYS_MODULE.MODULE_ORDER
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public BigDecimal getModuleOrder() {
        return moduleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.MODULE_ORDER
     *
     * @param moduleOrder the value for SYS_MODULE.MODULE_ORDER
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setModuleOrder(BigDecimal moduleOrder) {
        this.moduleOrder = moduleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.REMARK
     *
     * @return the value of SYS_MODULE.REMARK
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.REMARK
     *
     * @param remark the value for SYS_MODULE.REMARK
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.NEEDSELECTPROJECT
     *
     * @return the value of SYS_MODULE.NEEDSELECTPROJECT
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public BigDecimal getNeedselectproject() {
        return needselectproject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.NEEDSELECTPROJECT
     *
     * @param needselectproject the value for SYS_MODULE.NEEDSELECTPROJECT
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setNeedselectproject(BigDecimal needselectproject) {
        this.needselectproject = needselectproject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.MODULE_NAME_EN
     *
     * @return the value of SYS_MODULE.MODULE_NAME_EN
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public String getModuleNameEn() {
        return moduleNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.MODULE_NAME_EN
     *
     * @param moduleNameEn the value for SYS_MODULE.MODULE_NAME_EN
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setModuleNameEn(String moduleNameEn) {
        this.moduleNameEn = moduleNameEn == null ? null : moduleNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.ISCTRL
     *
     * @return the value of SYS_MODULE.ISCTRL
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public Short getIsctrl() {
        return isctrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.ISCTRL
     *
     * @param isctrl the value for SYS_MODULE.ISCTRL
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setIsctrl(Short isctrl) {
        this.isctrl = isctrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.HOME_MODULE_ID
     *
     * @return the value of SYS_MODULE.HOME_MODULE_ID
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public BigDecimal getHomeModuleId() {
        return homeModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.HOME_MODULE_ID
     *
     * @param homeModuleId the value for SYS_MODULE.HOME_MODULE_ID
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setHomeModuleId(BigDecimal homeModuleId) {
        this.homeModuleId = homeModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MODULE.SYSTEM_ID
     *
     * @return the value of SYS_MODULE.SYSTEM_ID
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public BigDecimal getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MODULE.SYSTEM_ID
     *
     * @param systemId the value for SYS_MODULE.SYSTEM_ID
     * @mbggenerated Mon Mar 06 14:06:59 CST 2017
     */
    public void setSystemId(BigDecimal systemId) {
        this.systemId = systemId;
    }
}