package com.springboot.demo.util.base.entitypo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

/**
 * 系统角色表
 **/
@Entity
public class SysRole extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ID
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    @Id
    @Column(nullable = false, length = 24)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.SYS_ID
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.SYS_NAME
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.CODE
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.NAME
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.REMARK
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.CREATOR_ID
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.CREATOR
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.CREATOR_DATE
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private Date creatorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.LAST_MODIFIER_ID
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String lastModifierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.LAST_MODIFIER
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String lastModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.LAST_MODIFIER_DATE
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private Date lastModifierDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ENABLE_STATE
     *
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    private String enableState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ID
     *
     * @return the value of SYS_ROLE.ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ID
     *
     * @param id the value for SYS_ROLE.ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.SYS_ID
     *
     * @return the value of SYS_ROLE.SYS_ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.SYS_ID
     *
     * @param sysId the value for SYS_ROLE.SYS_ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.SYS_NAME
     *
     * @return the value of SYS_ROLE.SYS_NAME
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.SYS_NAME
     *
     * @param sysName the value for SYS_ROLE.SYS_NAME
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.CODE
     *
     * @return the value of SYS_ROLE.CODE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.CODE
     *
     * @param code the value for SYS_ROLE.CODE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.NAME
     *
     * @return the value of SYS_ROLE.NAME
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.NAME
     *
     * @param name the value for SYS_ROLE.NAME
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.REMARK
     *
     * @return the value of SYS_ROLE.REMARK
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.REMARK
     *
     * @param remark the value for SYS_ROLE.REMARK
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.CREATOR_ID
     *
     * @return the value of SYS_ROLE.CREATOR_ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.CREATOR_ID
     *
     * @param creatorId the value for SYS_ROLE.CREATOR_ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.CREATOR
     *
     * @return the value of SYS_ROLE.CREATOR
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.CREATOR
     *
     * @param creator the value for SYS_ROLE.CREATOR
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.CREATOR_DATE
     *
     * @return the value of SYS_ROLE.CREATOR_DATE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public Date getCreatorDate() {
        return creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.CREATOR_DATE
     *
     * @param creatorDate the value for SYS_ROLE.CREATOR_DATE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setCreatorDate(Date creatorDate) {
        this.creatorDate = creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.LAST_MODIFIER_ID
     *
     * @return the value of SYS_ROLE.LAST_MODIFIER_ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getLastModifierId() {
        return lastModifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.LAST_MODIFIER_ID
     *
     * @param lastModifierId the value for SYS_ROLE.LAST_MODIFIER_ID
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setLastModifierId(String lastModifierId) {
        this.lastModifierId = lastModifierId == null ? null : lastModifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.LAST_MODIFIER
     *
     * @return the value of SYS_ROLE.LAST_MODIFIER
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.LAST_MODIFIER
     *
     * @param lastModifier the value for SYS_ROLE.LAST_MODIFIER
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.LAST_MODIFIER_DATE
     *
     * @return the value of SYS_ROLE.LAST_MODIFIER_DATE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public Date getLastModifierDate() {
        return lastModifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.LAST_MODIFIER_DATE
     *
     * @param lastModifierDate the value for SYS_ROLE.LAST_MODIFIER_DATE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setLastModifierDate(Date lastModifierDate) {
        this.lastModifierDate = lastModifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ENABLE_STATE
     *
     * @return the value of SYS_ROLE.ENABLE_STATE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public String getEnableState() {
        return enableState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ENABLE_STATE
     *
     * @param enableState the value for SYS_ROLE.ENABLE_STATE
     * @mbggenerated Mon Mar 06 14:07:03 CST 2017
     */
    public void setEnableState(String enableState) {
        this.enableState = enableState == null ? null : enableState.trim();
    }
}