package com.springboot.demo.util.base.entitypo;


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

/**
 * 系统用户表
 **/
@Entity
@DynamicUpdate(true)
public class SysUser extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.ID
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    @Id
    @Column(nullable = false, length = 24)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.CODE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.NAME
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.PASSWORD
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.TEL
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.MOBILE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.EMAIL
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.ENABLE_STATE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String enableState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.REMARK
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.CREATOR_ID
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.CREATOR
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.CREATOR_DATE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private Date creatorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.LAST_MODIFIER_ID
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String lastModifierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.LAST_MODIFIER
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String lastModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.LAST_MODIFIER_DATE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private Date lastModifierDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.USBKEY
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String usbkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.USER_TYPE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.CONTACTS
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.QQ
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.POSTCODE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.ADDRESS
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.REGURL
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String regurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.CITY
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.WECHAT
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.ORG_NAME
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.REGION
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.DISTRICT
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.IS_AVT
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String isAvt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.ENABLE_REMARK
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String enableRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.NUMBER_ID
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String numberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.DATA_SOURCE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.IS_SYNC_SUC
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String isSyncSuc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.DESCRIBE
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAT_USER.LAST_USE_PLAT_ID
     *
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    private String lastUsePlatId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.ID
     *
     * @return the value of CAT_USER.ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.ID
     *
     * @param id the value for CAT_USER.ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.CODE
     *
     * @return the value of CAT_USER.CODE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.CODE
     *
     * @param code the value for CAT_USER.CODE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.NAME
     *
     * @return the value of CAT_USER.NAME
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.NAME
     *
     * @param name the value for CAT_USER.NAME
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.PASSWORD
     *
     * @return the value of CAT_USER.PASSWORD
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.PASSWORD
     *
     * @param password the value for CAT_USER.PASSWORD
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.TEL
     *
     * @return the value of CAT_USER.TEL
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.TEL
     *
     * @param tel the value for CAT_USER.TEL
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.MOBILE
     *
     * @return the value of CAT_USER.MOBILE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.MOBILE
     *
     * @param mobile the value for CAT_USER.MOBILE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.EMAIL
     *
     * @return the value of CAT_USER.EMAIL
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.EMAIL
     *
     * @param email the value for CAT_USER.EMAIL
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.ENABLE_STATE
     *
     * @return the value of CAT_USER.ENABLE_STATE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getEnableState() {
        return enableState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.ENABLE_STATE
     *
     * @param enableState the value for CAT_USER.ENABLE_STATE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setEnableState(String enableState) {
        this.enableState = enableState == null ? null : enableState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.REMARK
     *
     * @return the value of CAT_USER.REMARK
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.REMARK
     *
     * @param remark the value for CAT_USER.REMARK
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.CREATOR_ID
     *
     * @return the value of CAT_USER.CREATOR_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.CREATOR_ID
     *
     * @param creatorId the value for CAT_USER.CREATOR_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.CREATOR
     *
     * @return the value of CAT_USER.CREATOR
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.CREATOR
     *
     * @param creator the value for CAT_USER.CREATOR
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.CREATOR_DATE
     *
     * @return the value of CAT_USER.CREATOR_DATE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public Date getCreatorDate() {
        return creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.CREATOR_DATE
     *
     * @param creatorDate the value for CAT_USER.CREATOR_DATE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setCreatorDate(Date creatorDate) {
        this.creatorDate = creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.LAST_MODIFIER_ID
     *
     * @return the value of CAT_USER.LAST_MODIFIER_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getLastModifierId() {
        return lastModifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.LAST_MODIFIER_ID
     *
     * @param lastModifierId the value for CAT_USER.LAST_MODIFIER_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setLastModifierId(String lastModifierId) {
        this.lastModifierId = lastModifierId == null ? null : lastModifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.LAST_MODIFIER
     *
     * @return the value of CAT_USER.LAST_MODIFIER
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.LAST_MODIFIER
     *
     * @param lastModifier the value for CAT_USER.LAST_MODIFIER
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.LAST_MODIFIER_DATE
     *
     * @return the value of CAT_USER.LAST_MODIFIER_DATE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public Date getLastModifierDate() {
        return lastModifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.LAST_MODIFIER_DATE
     *
     * @param lastModifierDate the value for CAT_USER.LAST_MODIFIER_DATE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setLastModifierDate(Date lastModifierDate) {
        this.lastModifierDate = lastModifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.USBKEY
     *
     * @return the value of CAT_USER.USBKEY
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getUsbkey() {
        return usbkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.USBKEY
     *
     * @param usbkey the value for CAT_USER.USBKEY
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setUsbkey(String usbkey) {
        this.usbkey = usbkey == null ? null : usbkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.USER_TYPE
     *
     * @return the value of CAT_USER.USER_TYPE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.USER_TYPE
     *
     * @param userType the value for CAT_USER.USER_TYPE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.CONTACTS
     *
     * @return the value of CAT_USER.CONTACTS
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.CONTACTS
     *
     * @param contacts the value for CAT_USER.CONTACTS
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.QQ
     *
     * @return the value of CAT_USER.QQ
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.QQ
     *
     * @param qq the value for CAT_USER.QQ
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.POSTCODE
     *
     * @return the value of CAT_USER.POSTCODE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.POSTCODE
     *
     * @param postcode the value for CAT_USER.POSTCODE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.ADDRESS
     *
     * @return the value of CAT_USER.ADDRESS
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.ADDRESS
     *
     * @param address the value for CAT_USER.ADDRESS
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.REGURL
     *
     * @return the value of CAT_USER.REGURL
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getRegurl() {
        return regurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.REGURL
     *
     * @param regurl the value for CAT_USER.REGURL
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setRegurl(String regurl) {
        this.regurl = regurl == null ? null : regurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.CITY
     *
     * @return the value of CAT_USER.CITY
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.CITY
     *
     * @param city the value for CAT_USER.CITY
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.WECHAT
     *
     * @return the value of CAT_USER.WECHAT
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.WECHAT
     *
     * @param wechat the value for CAT_USER.WECHAT
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.ORG_NAME
     *
     * @return the value of CAT_USER.ORG_NAME
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.ORG_NAME
     *
     * @param orgName the value for CAT_USER.ORG_NAME
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.REGION
     *
     * @return the value of CAT_USER.REGION
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.REGION
     *
     * @param region the value for CAT_USER.REGION
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.DISTRICT
     *
     * @return the value of CAT_USER.DISTRICT
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.DISTRICT
     *
     * @param district the value for CAT_USER.DISTRICT
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.IS_AVT
     *
     * @return the value of CAT_USER.IS_AVT
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getIsAvt() {
        return isAvt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.IS_AVT
     *
     * @param isAvt the value for CAT_USER.IS_AVT
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setIsAvt(String isAvt) {
        this.isAvt = isAvt == null ? null : isAvt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.ENABLE_REMARK
     *
     * @return the value of CAT_USER.ENABLE_REMARK
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getEnableRemark() {
        return enableRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.ENABLE_REMARK
     *
     * @param enableRemark the value for CAT_USER.ENABLE_REMARK
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setEnableRemark(String enableRemark) {
        this.enableRemark = enableRemark == null ? null : enableRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.NUMBER_ID
     *
     * @return the value of CAT_USER.NUMBER_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getNumberId() {
        return numberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.NUMBER_ID
     *
     * @param numberId the value for CAT_USER.NUMBER_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setNumberId(String numberId) {
        this.numberId = numberId == null ? null : numberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.DATA_SOURCE
     *
     * @return the value of CAT_USER.DATA_SOURCE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.DATA_SOURCE
     *
     * @param dataSource the value for CAT_USER.DATA_SOURCE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.IS_SYNC_SUC
     *
     * @return the value of CAT_USER.IS_SYNC_SUC
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getIsSyncSuc() {
        return isSyncSuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.IS_SYNC_SUC
     *
     * @param isSyncSuc the value for CAT_USER.IS_SYNC_SUC
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setIsSyncSuc(String isSyncSuc) {
        this.isSyncSuc = isSyncSuc == null ? null : isSyncSuc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.DESCRIBE
     *
     * @return the value of CAT_USER.DESCRIBE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.DESCRIBE
     *
     * @param describe the value for CAT_USER.DESCRIBE
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAT_USER.LAST_USE_PLAT_ID
     *
     * @return the value of CAT_USER.LAST_USE_PLAT_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public String getLastUsePlatId() {
        return lastUsePlatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAT_USER.LAST_USE_PLAT_ID
     *
     * @param lastUsePlatId the value for CAT_USER.LAST_USE_PLAT_ID
     * @mbggenerated Mon Mar 06 14:06:57 CST 2017
     */
    public void setLastUsePlatId(String lastUsePlatId) {
        this.lastUsePlatId = lastUsePlatId == null ? null : lastUsePlatId.trim();
    }
}