package com.springboot.demo.util.base.entitypo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * 系统用户角色表
 **/
@Entity
public class SysUserAuth extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_AUTH.ID
     *
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    @Id
    @Column(nullable = false, length = 24)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_AUTH.USER_ID
     *
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_AUTH.ROLE_ID
     *
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_AUTH.SYS_ID
     *
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    private String sysId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_AUTH.ID
     *
     * @return the value of SYS_USER_AUTH.ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_AUTH.ID
     *
     * @param id the value for SYS_USER_AUTH.ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_AUTH.USER_ID
     *
     * @return the value of SYS_USER_AUTH.USER_ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_AUTH.USER_ID
     *
     * @param userId the value for SYS_USER_AUTH.USER_ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_AUTH.ROLE_ID
     *
     * @return the value of SYS_USER_AUTH.ROLE_ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_AUTH.ROLE_ID
     *
     * @param roleId the value for SYS_USER_AUTH.ROLE_ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_AUTH.SYS_ID
     *
     * @return the value of SYS_USER_AUTH.SYS_ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_AUTH.SYS_ID
     *
     * @param sysId the value for SYS_USER_AUTH.SYS_ID
     * @mbggenerated Mon Mar 06 14:07:04 CST 2017
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }
}